In [205]:

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
import numpy as np 
import keras
import random

print("keras version"+keras.__version__)

keras version2.0.6


In [206]:
def genData():
  a1=random.randint(0,127)
  a2=random.randint(0,127)
  a3=a1+a2
  tmp1=np.unpackbits(np.uint8(a1))
  tmp2=np.unpackbits(np.uint8(a2))
  y=np.unpackbits(np.uint8(a3))
  X=np.concatenate((tmp1, tmp2))
  y=np.expand_dims(y,0)
  X=np.expand_dims(X,0)
  return(X,y)


In [207]:
def overlap(X_train, X_test):
  cnt=0
  for i in range(np.shape(X_test)[0]):
    i=0
    iv= X_test[i,:]
    #print(iv)
    for k in  range(np.shape(X_train)[0]):
      kv=X_train[k,:]
      #print(kv)
      if np.all(iv==kv):
        cnt=cnt+1
  return(cnt)  

In [214]:
tmpX, tmpy=genData()
X=tmpX
y=tmpy
# Note the total combination is 127 x 127
NumSample=1000
print("Sample Percentage: "+str(NumSample/(127.*127.)*100))
for i in range(NumSample-1):
  tmpX, tmpy=genData()
  X=np.insert(X, 1, tmpX, axis=0)
  y=np.insert(y, 1, tmpy, axis=0)



Sample Percentage: 6.20001240002


In [215]:

input_dim=np.shape(X)[1]
print("input_dim: "+str(input_dim))
output_dim=np.shape(y)[1]
print("output_dim: "+str(output_dim))



input_dim: 16
output_dim: 8


In [216]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [217]:
model = Sequential()
model.add(Dense(20, input_dim=input_dim))
model.add(Activation('tanh'))
model.add(Dense(20, input_dim=8))
model.add(Activation('tanh'))
model.add(Dense(output_dim))
model.add(Activation('sigmoid'))

sgd = SGD(lr=0.1)
model.compile(loss='binary_crossentropy', 
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=4, epochs=1000, verbose=0)
print("finished")

finished


In [222]:
# Check with how much X_test overlaps X_train
print("Overlap Percentage: "+str(overlap(X_train, X_test)))

Overlap Percentage: 0


In [219]:
score = model.evaluate(X_test, y_test, batch_size=4)
print(score)
# predict(self, x, batch_size=32, verbose=0)


244/330 [=====================>........] - ETA: 0s[0.021262432914932794, 0.99431818181818177]


In [227]:
# You may examine the result
dx=0
print(X_test[dx,0:8])
print("+")
print(X_test[dx,8:16])
print("----------------")
print(model.predict(np.expand_dims(X_test[dx,:],0)))
print("label is")
print(y_test[dx,:])
'''
[0 0 1 1 0 0 0 0]
+
[0 0 0 0 0 1 1 1]
----------------
[[  9.57744305e-06   9.10499715e-04   9.99716103e-01   9.99986053e-01
    1.64891779e-03   9.99194443e-01   9.99991775e-01   9.99949098e-01]]
label is
[0 0 1 1 0 1 1 1]
'''

[0 0 1 1 0 0 0 0]
+
[0 0 0 0 0 1 1 1]
----------------
[[  9.57744305e-06   9.10499715e-04   9.99716103e-01   9.99986053e-01
    1.64891779e-03   9.99194443e-01   9.99991775e-01   9.99949098e-01]]
label is
[0 0 1 1 0 1 1 1]
